"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module

if TYPE_CHECKING:
    from .audiomodalitydata import AudioModalityData, AudioModalityDataTypedDict
    from .connection import (
        Connection,
        ConnectionMetadata,
        ConnectionMetadataTypedDict,
        ConnectionTypedDict,
        DisabledBySystemReason,
        Source,
        SourceTypedDict,
    )
    from .connectionbase import (
        ConnectionBase,
        ConnectionBaseMetadata,
        ConnectionBaseMetadataTypedDict,
        ConnectionBaseTypedDict,
        PartitionStrategy,
        PartitionStrategy1,
        PartitionStrategyTypedDict,
    )
    from .connectionlimitexceededwebhook import (
        ConnectionLimitExceededWebhook,
        ConnectionLimitExceededWebhookTypedDict,
    )
    from .connectionlimitexceededwebhookpayload import (
        ConnectionLimitExceededWebhookPayload,
        ConnectionLimitExceededWebhookPayloadTypedDict,
    )
    from .connectionlimitparams import (
        ConnectionLimitParams,
        ConnectionLimitParamsTypedDict,
    )
    from .connectionlist import ConnectionList, ConnectionListTypedDict
    from .connectionstats import ConnectionStats, ConnectionStatsTypedDict
    from .connectionsyncfinishedwebhook import (
        ConnectionSyncFinishedWebhook,
        ConnectionSyncFinishedWebhookTypedDict,
    )
    from .connectionsyncfinishedwebhookpayload import (
        ConnectionSyncFinishedWebhookPayload,
        ConnectionSyncFinishedWebhookPayloadTypedDict,
    )
    from .connectionsyncprogresswebhook import (
        ConnectionSyncProgressWebhook,
        ConnectionSyncProgressWebhookTypedDict,
    )
    from .connectionsyncprogresswebhookpayload import (
        ConnectionSyncProgressWebhookPayload,
        ConnectionSyncProgressWebhookPayloadTypedDict,
    )
    from .connectionsyncstartedwebhook import (
        ConnectionSyncStartedWebhook,
        ConnectionSyncStartedWebhookTypedDict,
    )
    from .connectionsyncstartedwebhookpayload import (
        ConnectionSyncStartedWebhookPayload,
        ConnectionSyncStartedWebhookPayloadTypedDict,
    )
    from .connectorsource import ConnectorSource
    from .connectorsourcetypeinfo import (
        ConnectorSourceTypeInfo,
        ConnectorSourceTypeInfoTypedDict,
    )
    from .createdocumentfromurlparams import (
        CreateDocumentFromURLParams,
        CreateDocumentFromURLParamsMetadata,
        CreateDocumentFromURLParamsMetadataTypedDict,
        CreateDocumentFromURLParamsMode,
        CreateDocumentFromURLParamsModeTypedDict,
        CreateDocumentFromURLParamsTypedDict,
        Mode1,
    )
    from .createdocumentparams import (
        CreateDocumentParams,
        CreateDocumentParamsTypedDict,
        File,
        FileTypedDict,
        Metadata,
        MetadataTypedDict,
        Mode,
        ModeStatic,
        ModeTypedDict,
        ModeVideo,
        One,
        One1,
        One2,
        One2TypedDict,
        OneTypedDict,
        Two,
        TwoTypedDict,
    )
    from .createdocumentrawparams import (
        CreateDocumentRawParams,
        CreateDocumentRawParamsMetadata,
        CreateDocumentRawParamsMetadataTypedDict,
        CreateDocumentRawParamsTypedDict,
        Data,
        DataTypedDict,
    )
    from .createinstructionparams import (
        CreateInstructionParams,
        CreateInstructionParamsScope,
        CreateInstructionParamsTypedDict,
    )
    from .createpartitionparams import (
        CreatePartitionParams,
        CreatePartitionParamsTypedDict,
    )
    from .delete_connection_connections_connection_id_delete_postop import (
        DeleteConnectionConnectionsConnectionIDDeletePostRequest,
        DeleteConnectionConnectionsConnectionIDDeletePostRequestTypedDict,
    )
    from .delete_partition_partitions_partition_id_deleteop import (
        DeletePartitionPartitionsPartitionIDDeleteRequest,
        DeletePartitionPartitionsPartitionIDDeleteRequestTypedDict,
    )
    from .deleteconnectionpayload import (
        DeleteConnectionPayload,
        DeleteConnectionPayloadTypedDict,
    )
    from .deletedocumentop import DeleteDocumentRequest, DeleteDocumentRequestTypedDict
    from .deleteinstructionop import (
        DeleteInstructionRequest,
        DeleteInstructionRequestTypedDict,
    )
    from .document import (
        Document,
        DocumentMetadata,
        DocumentMetadataTypedDict,
        DocumentTypedDict,
    )
    from .documentchunk import DocumentChunk, DocumentChunkTypedDict
    from .documentchunkdetail import (
        DocumentChunkDetail,
        DocumentChunkDetailTypedDict,
        ModalityData,
        ModalityDataTypedDict,
    )
    from .documentchunklist import DocumentChunkList, DocumentChunkListTypedDict
    from .documentdelete import DocumentDelete, DocumentDeleteTypedDict
    from .documentdeletewebhook import (
        DocumentDeleteWebhook,
        DocumentDeleteWebhookTypedDict,
    )
    from .documentdeletewebhookpayload import (
        DocumentDeleteWebhookPayload,
        DocumentDeleteWebhookPayloadTypedDict,
    )
    from .documentfileupdate import DocumentFileUpdate, DocumentFileUpdateTypedDict
    from .documentget import (
        DocumentGet,
        DocumentGetMetadata,
        DocumentGetMetadataTypedDict,
        DocumentGetTypedDict,
    )
    from .documentlist import DocumentList, DocumentListTypedDict
    from .documentmetadataupdate import (
        DocumentMetadataUpdate,
        DocumentMetadataUpdateMetadata,
        DocumentMetadataUpdateMetadataTypedDict,
        DocumentMetadataUpdateTypedDict,
    )
    from .documentrawupdate import DocumentRawUpdate, DocumentRawUpdateTypedDict
    from .documentsummary import DocumentSummary, DocumentSummaryTypedDict
    from .documentupdatewebhook import (
        DocumentUpdateWebhook,
        DocumentUpdateWebhookTypedDict,
    )
    from .documentupdatewebhookpayload import (
        DocumentUpdateWebhookPayload,
        DocumentUpdateWebhookPayloadTypedDict,
    )
    from .documenturlupdate import DocumentURLUpdate, DocumentURLUpdateTypedDict
    from .documentwithcontent import (
        DocumentWithContent,
        DocumentWithContentMetadata,
        DocumentWithContentMetadataTypedDict,
        DocumentWithContentTypedDict,
    )
    from .entity import Entity, EntityTypedDict
    from .entityextractedwebhook import (
        EntityExtractedWebhook,
        EntityExtractedWebhookTypedDict,
    )
    from .entityextractedwebhookpayload import (
        EntityExtractedWebhookPayload,
        EntityExtractedWebhookPayloadTypedDict,
    )
    from .entitylist import EntityList, EntityListTypedDict
    from .errormessage import ErrorMessage, ErrorMessageData
    from .eventevent_postop import EventeventPostBody, EventeventPostBodyTypedDict
    from .get_connection_connections_connection_id_getop import (
        GetConnectionConnectionsConnectionIDGetRequest,
        GetConnectionConnectionsConnectionIDGetRequestTypedDict,
    )
    from .get_connection_stats_connections_connection_id_stats_getop import (
        GetConnectionStatsConnectionsConnectionIDStatsGetRequest,
        GetConnectionStatsConnectionsConnectionIDStatsGetRequestTypedDict,
    )
    from .get_partition_partitions_partition_id_getop import (
        GetPartitionPartitionsPartitionIDGetRequest,
        GetPartitionPartitionsPartitionIDGetRequestTypedDict,
    )
    from .getdocumentchunkcontentop import (
        GetDocumentChunkContentRequest,
        GetDocumentChunkContentRequestTypedDict,
        MediaType,
    )
    from .getdocumentchunkop import (
        GetDocumentChunkRequest,
        GetDocumentChunkRequestTypedDict,
    )
    from .getdocumentchunksop import (
        GetDocumentChunksRequest,
        GetDocumentChunksRequestTypedDict,
    )
    from .getdocumentcontentop import (
        GetDocumentContentRequest,
        GetDocumentContentRequestTypedDict,
        QueryParam1,
        QueryParamMediaType,
        QueryParamMediaTypeTypedDict,
    )
    from .getdocumentop import GetDocumentRequest, GetDocumentRequestTypedDict
    from .getdocumentsourceop import (
        GetDocumentSourceRequest,
        GetDocumentSourceRequestTypedDict,
    )
    from .getdocumentsummaryop import (
        GetDocumentSummaryRequest,
        GetDocumentSummaryRequestTypedDict,
    )
    from .httpvalidationerror import HTTPValidationError, HTTPValidationErrorData
    from .instruction import Instruction, InstructionTypedDict, Scope
    from .link import Link, LinkTypedDict
    from .list_connections_connections_getop import (
        ListConnectionsConnectionsGetRequest,
        ListConnectionsConnectionsGetRequestTypedDict,
        ListConnectionsConnectionsGetResponse,
        ListConnectionsConnectionsGetResponseTypedDict,
    )
    from .list_partitions_partitions_getop import (
        ListPartitionsPartitionsGetRequest,
        ListPartitionsPartitionsGetRequestTypedDict,
        ListPartitionsPartitionsGetResponse,
        ListPartitionsPartitionsGetResponseTypedDict,
    )
    from .listconnectorsourcetypeinfo import (
        ListConnectorSourceTypeInfo,
        ListConnectorSourceTypeInfoTypedDict,
    )
    from .listdocumentsop import (
        ListDocumentsRequest,
        ListDocumentsRequestTypedDict,
        ListDocumentsResponse,
        ListDocumentsResponseTypedDict,
    )
    from .listentitiesbydocumentop import (
        ListEntitiesByDocumentRequest,
        ListEntitiesByDocumentRequestTypedDict,
        ListEntitiesByDocumentResponse,
        ListEntitiesByDocumentResponseTypedDict,
    )
    from .listentitiesbyinstructionop import (
        ListEntitiesByInstructionRequest,
        ListEntitiesByInstructionRequestTypedDict,
        ListEntitiesByInstructionResponse,
        ListEntitiesByInstructionResponseTypedDict,
    )
    from .mediamodeparam import MediaModeParam, MediaModeParamTypedDict, Static, Video
    from .oauthurlcreate import (
        OAuthURLCreate,
        OAuthURLCreateMetadata,
        OAuthURLCreateMetadataTypedDict,
        OAuthURLCreateMode,
        OAuthURLCreateMode1,
        OAuthURLCreateModeTypedDict,
        OAuthURLCreateTypedDict,
        Theme,
    )
    from .oauthurlresponse import OAuthURLResponse, OAuthURLResponseTypedDict
    from .pagination import Pagination, PaginationTypedDict
    from .partition import Partition, PartitionTypedDict
    from .partitiondetail import PartitionDetail, PartitionDetailTypedDict
    from .partitionlimitexceededwebhook import (
        PartitionLimitExceededWebhook,
        PartitionLimitExceededWebhookTypedDict,
    )
    from .partitionlimitexceededwebhookpayload import (
        LimitType,
        PartitionLimitExceededWebhookPayload,
        PartitionLimitExceededWebhookPayloadTypedDict,
    )
    from .partitionlimitparams import (
        PartitionLimitParams,
        PartitionLimitParamsTypedDict,
    )
    from .partitionlimits import PartitionLimits, PartitionLimitsTypedDict
    from .partitionlist import PartitionList, PartitionListTypedDict
    from .partitionstats import PartitionStats, PartitionStatsTypedDict
    from .patchdocumentmetadataop import (
        PatchDocumentMetadataRequest,
        PatchDocumentMetadataRequestTypedDict,
    )
    from .patchdocumentmetadataparams import (
        PatchDocumentMetadataParams,
        PatchDocumentMetadataParamsTypedDict,
    )
    from .responseok import ResponseOK, ResponseOKTypedDict
    from .retrieval import Retrieval, RetrievalTypedDict
    from .retrieveparams import RetrieveParams, RetrieveParamsTypedDict
    from .scoredchunk import ScoredChunk, ScoredChunkTypedDict
    from .sdkerror import SDKError
    from .security import Security, SecurityTypedDict
    from .set_connection_enabled_connections_connection_id_enabled_putop import (
        SetConnectionEnabledConnectionsConnectionIDEnabledPutRequest,
        SetConnectionEnabledConnectionsConnectionIDEnabledPutRequestTypedDict,
    )
    from .set_connection_limits_connections_connection_id_limit_putop import (
        SetConnectionLimitsConnectionsConnectionIDLimitPutRequest,
        SetConnectionLimitsConnectionsConnectionIDLimitPutRequestTypedDict,
    )
    from .set_partition_limits_partitions_partition_id_limits_putop import (
        SetPartitionLimitsPartitionsPartitionIDLimitsPutRequest,
        SetPartitionLimitsPartitionsPartitionIDLimitsPutRequestTypedDict,
    )
    from .setconnectionenabledpayload import (
        Reason,
        SetConnectionEnabledPayload,
        SetConnectionEnabledPayloadTypedDict,
    )
    from .syncconnectionop import SyncConnectionRequest, SyncConnectionRequestTypedDict
    from .update_connection_connections_connection_id_putop import (
        UpdateConnectionConnectionsConnectionIDPutRequest,
        UpdateConnectionConnectionsConnectionIDPutRequestTypedDict,
    )
    from .updatedocumentfileop import (
        UpdateDocumentFileRequest,
        UpdateDocumentFileRequestTypedDict,
    )
    from .updatedocumentfileparams import (
        Mode2,
        Mode2TypedDict,
        UpdateDocumentFileParams,
        UpdateDocumentFileParams11,
        UpdateDocumentFileParams12,
        UpdateDocumentFileParams12TypedDict,
        UpdateDocumentFileParamsFile,
        UpdateDocumentFileParamsFileTypedDict,
        UpdateDocumentFileParamsMode,
        UpdateDocumentFileParamsMode1,
        UpdateDocumentFileParamsMode1TypedDict,
        UpdateDocumentFileParamsModeStatic,
        UpdateDocumentFileParamsModeTypedDict,
        UpdateDocumentFileParamsModeVideo,
        UpdateDocumentFileParamsTypedDict,
    )
    from .updatedocumentfromurlop import (
        UpdateDocumentFromURLRequest,
        UpdateDocumentFromURLRequestTypedDict,
    )
    from .updatedocumentfromurlparams import (
        UpdateDocumentFromURLParams,
        UpdateDocumentFromURLParamsMode,
        UpdateDocumentFromURLParamsMode1,
        UpdateDocumentFromURLParamsModeTypedDict,
        UpdateDocumentFromURLParamsTypedDict,
    )
    from .updatedocumentrawop import (
        UpdateDocumentRawRequest,
        UpdateDocumentRawRequestTypedDict,
    )
    from .updatedocumentrawparams import (
        UpdateDocumentRawParams,
        UpdateDocumentRawParamsData,
        UpdateDocumentRawParamsDataTypedDict,
        UpdateDocumentRawParamsTypedDict,
    )
    from .updateinstructionop import (
        UpdateInstructionRequest,
        UpdateInstructionRequestTypedDict,
    )
    from .updateinstructionparams import (
        UpdateInstructionParams,
        UpdateInstructionParamsTypedDict,
    )
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .videomodalitydata import VideoModalityData, VideoModalityDataTypedDict
    from .wordtimestamp import WordTimestamp, WordTimestampTypedDict

__all__ = [
    "AudioModalityData",
    "AudioModalityDataTypedDict",
    "Connection",
    "ConnectionBase",
    "ConnectionBaseMetadata",
    "ConnectionBaseMetadataTypedDict",
    "ConnectionBaseTypedDict",
    "ConnectionLimitExceededWebhook",
    "ConnectionLimitExceededWebhookPayload",
    "ConnectionLimitExceededWebhookPayloadTypedDict",
    "ConnectionLimitExceededWebhookTypedDict",
    "ConnectionLimitParams",
    "ConnectionLimitParamsTypedDict",
    "ConnectionList",
    "ConnectionListTypedDict",
    "ConnectionMetadata",
    "ConnectionMetadataTypedDict",
    "ConnectionStats",
    "ConnectionStatsTypedDict",
    "ConnectionSyncFinishedWebhook",
    "ConnectionSyncFinishedWebhookPayload",
    "ConnectionSyncFinishedWebhookPayloadTypedDict",
    "ConnectionSyncFinishedWebhookTypedDict",
    "ConnectionSyncProgressWebhook",
    "ConnectionSyncProgressWebhookPayload",
    "ConnectionSyncProgressWebhookPayloadTypedDict",
    "ConnectionSyncProgressWebhookTypedDict",
    "ConnectionSyncStartedWebhook",
    "ConnectionSyncStartedWebhookPayload",
    "ConnectionSyncStartedWebhookPayloadTypedDict",
    "ConnectionSyncStartedWebhookTypedDict",
    "ConnectionTypedDict",
    "ConnectorSource",
    "ConnectorSourceTypeInfo",
    "ConnectorSourceTypeInfoTypedDict",
    "CreateDocumentFromURLParams",
    "CreateDocumentFromURLParamsMetadata",
    "CreateDocumentFromURLParamsMetadataTypedDict",
    "CreateDocumentFromURLParamsMode",
    "CreateDocumentFromURLParamsModeTypedDict",
    "CreateDocumentFromURLParamsTypedDict",
    "CreateDocumentParams",
    "CreateDocumentParamsTypedDict",
    "CreateDocumentRawParams",
    "CreateDocumentRawParamsMetadata",
    "CreateDocumentRawParamsMetadataTypedDict",
    "CreateDocumentRawParamsTypedDict",
    "CreateInstructionParams",
    "CreateInstructionParamsScope",
    "CreateInstructionParamsTypedDict",
    "CreatePartitionParams",
    "CreatePartitionParamsTypedDict",
    "Data",
    "DataTypedDict",
    "DeleteConnectionConnectionsConnectionIDDeletePostRequest",
    "DeleteConnectionConnectionsConnectionIDDeletePostRequestTypedDict",
    "DeleteConnectionPayload",
    "DeleteConnectionPayloadTypedDict",
    "DeleteDocumentRequest",
    "DeleteDocumentRequestTypedDict",
    "DeleteInstructionRequest",
    "DeleteInstructionRequestTypedDict",
    "DeletePartitionPartitionsPartitionIDDeleteRequest",
    "DeletePartitionPartitionsPartitionIDDeleteRequestTypedDict",
    "DisabledBySystemReason",
    "Document",
    "DocumentChunk",
    "DocumentChunkDetail",
    "DocumentChunkDetailTypedDict",
    "DocumentChunkList",
    "DocumentChunkListTypedDict",
    "DocumentChunkTypedDict",
    "DocumentDelete",
    "DocumentDeleteTypedDict",
    "DocumentDeleteWebhook",
    "DocumentDeleteWebhookPayload",
    "DocumentDeleteWebhookPayloadTypedDict",
    "DocumentDeleteWebhookTypedDict",
    "DocumentFileUpdate",
    "DocumentFileUpdateTypedDict",
    "DocumentGet",
    "DocumentGetMetadata",
    "DocumentGetMetadataTypedDict",
    "DocumentGetTypedDict",
    "DocumentList",
    "DocumentListTypedDict",
    "DocumentMetadata",
    "DocumentMetadataTypedDict",
    "DocumentMetadataUpdate",
    "DocumentMetadataUpdateMetadata",
    "DocumentMetadataUpdateMetadataTypedDict",
    "DocumentMetadataUpdateTypedDict",
    "DocumentRawUpdate",
    "DocumentRawUpdateTypedDict",
    "DocumentSummary",
    "DocumentSummaryTypedDict",
    "DocumentTypedDict",
    "DocumentURLUpdate",
    "DocumentURLUpdateTypedDict",
    "DocumentUpdateWebhook",
    "DocumentUpdateWebhookPayload",
    "DocumentUpdateWebhookPayloadTypedDict",
    "DocumentUpdateWebhookTypedDict",
    "DocumentWithContent",
    "DocumentWithContentMetadata",
    "DocumentWithContentMetadataTypedDict",
    "DocumentWithContentTypedDict",
    "Entity",
    "EntityExtractedWebhook",
    "EntityExtractedWebhookPayload",
    "EntityExtractedWebhookPayloadTypedDict",
    "EntityExtractedWebhookTypedDict",
    "EntityList",
    "EntityListTypedDict",
    "EntityTypedDict",
    "ErrorMessage",
    "ErrorMessageData",
    "EventeventPostBody",
    "EventeventPostBodyTypedDict",
    "File",
    "FileTypedDict",
    "GetConnectionConnectionsConnectionIDGetRequest",
    "GetConnectionConnectionsConnectionIDGetRequestTypedDict",
    "GetConnectionStatsConnectionsConnectionIDStatsGetRequest",
    "GetConnectionStatsConnectionsConnectionIDStatsGetRequestTypedDict",
    "GetDocumentChunkContentRequest",
    "GetDocumentChunkContentRequestTypedDict",
    "GetDocumentChunkRequest",
    "GetDocumentChunkRequestTypedDict",
    "GetDocumentChunksRequest",
    "GetDocumentChunksRequestTypedDict",
    "GetDocumentContentRequest",
    "GetDocumentContentRequestTypedDict",
    "GetDocumentRequest",
    "GetDocumentRequestTypedDict",
    "GetDocumentSourceRequest",
    "GetDocumentSourceRequestTypedDict",
    "GetDocumentSummaryRequest",
    "GetDocumentSummaryRequestTypedDict",
    "GetPartitionPartitionsPartitionIDGetRequest",
    "GetPartitionPartitionsPartitionIDGetRequestTypedDict",
    "HTTPValidationError",
    "HTTPValidationErrorData",
    "Instruction",
    "InstructionTypedDict",
    "LimitType",
    "Link",
    "LinkTypedDict",
    "ListConnectionsConnectionsGetRequest",
    "ListConnectionsConnectionsGetRequestTypedDict",
    "ListConnectionsConnectionsGetResponse",
    "ListConnectionsConnectionsGetResponseTypedDict",
    "ListConnectorSourceTypeInfo",
    "ListConnectorSourceTypeInfoTypedDict",
    "ListDocumentsRequest",
    "ListDocumentsRequestTypedDict",
    "ListDocumentsResponse",
    "ListDocumentsResponseTypedDict",
    "ListEntitiesByDocumentRequest",
    "ListEntitiesByDocumentRequestTypedDict",
    "ListEntitiesByDocumentResponse",
    "ListEntitiesByDocumentResponseTypedDict",
    "ListEntitiesByInstructionRequest",
    "ListEntitiesByInstructionRequestTypedDict",
    "ListEntitiesByInstructionResponse",
    "ListEntitiesByInstructionResponseTypedDict",
    "ListPartitionsPartitionsGetRequest",
    "ListPartitionsPartitionsGetRequestTypedDict",
    "ListPartitionsPartitionsGetResponse",
    "ListPartitionsPartitionsGetResponseTypedDict",
    "Loc",
    "LocTypedDict",
    "MediaModeParam",
    "MediaModeParamTypedDict",
    "MediaType",
    "Metadata",
    "MetadataTypedDict",
    "ModalityData",
    "ModalityDataTypedDict",
    "Mode",
    "Mode1",
    "Mode2",
    "Mode2TypedDict",
    "ModeStatic",
    "ModeTypedDict",
    "ModeVideo",
    "OAuthURLCreate",
    "OAuthURLCreateMetadata",
    "OAuthURLCreateMetadataTypedDict",
    "OAuthURLCreateMode",
    "OAuthURLCreateMode1",
    "OAuthURLCreateModeTypedDict",
    "OAuthURLCreateTypedDict",
    "OAuthURLResponse",
    "OAuthURLResponseTypedDict",
    "One",
    "One1",
    "One2",
    "One2TypedDict",
    "OneTypedDict",
    "Pagination",
    "PaginationTypedDict",
    "Partition",
    "PartitionDetail",
    "PartitionDetailTypedDict",
    "PartitionLimitExceededWebhook",
    "PartitionLimitExceededWebhookPayload",
    "PartitionLimitExceededWebhookPayloadTypedDict",
    "PartitionLimitExceededWebhookTypedDict",
    "PartitionLimitParams",
    "PartitionLimitParamsTypedDict",
    "PartitionLimits",
    "PartitionLimitsTypedDict",
    "PartitionList",
    "PartitionListTypedDict",
    "PartitionStats",
    "PartitionStatsTypedDict",
    "PartitionStrategy",
    "PartitionStrategy1",
    "PartitionStrategyTypedDict",
    "PartitionTypedDict",
    "PatchDocumentMetadataParams",
    "PatchDocumentMetadataParamsTypedDict",
    "PatchDocumentMetadataRequest",
    "PatchDocumentMetadataRequestTypedDict",
    "QueryParam1",
    "QueryParamMediaType",
    "QueryParamMediaTypeTypedDict",
    "Reason",
    "ResponseOK",
    "ResponseOKTypedDict",
    "Retrieval",
    "RetrievalTypedDict",
    "RetrieveParams",
    "RetrieveParamsTypedDict",
    "SDKError",
    "Scope",
    "ScoredChunk",
    "ScoredChunkTypedDict",
    "Security",
    "SecurityTypedDict",
    "SetConnectionEnabledConnectionsConnectionIDEnabledPutRequest",
    "SetConnectionEnabledConnectionsConnectionIDEnabledPutRequestTypedDict",
    "SetConnectionEnabledPayload",
    "SetConnectionEnabledPayloadTypedDict",
    "SetConnectionLimitsConnectionsConnectionIDLimitPutRequest",
    "SetConnectionLimitsConnectionsConnectionIDLimitPutRequestTypedDict",
    "SetPartitionLimitsPartitionsPartitionIDLimitsPutRequest",
    "SetPartitionLimitsPartitionsPartitionIDLimitsPutRequestTypedDict",
    "Source",
    "SourceTypedDict",
    "Static",
    "SyncConnectionRequest",
    "SyncConnectionRequestTypedDict",
    "Theme",
    "Two",
    "TwoTypedDict",
    "UpdateConnectionConnectionsConnectionIDPutRequest",
    "UpdateConnectionConnectionsConnectionIDPutRequestTypedDict",
    "UpdateDocumentFileParams",
    "UpdateDocumentFileParams11",
    "UpdateDocumentFileParams12",
    "UpdateDocumentFileParams12TypedDict",
    "UpdateDocumentFileParamsFile",
    "UpdateDocumentFileParamsFileTypedDict",
    "UpdateDocumentFileParamsMode",
    "UpdateDocumentFileParamsMode1",
    "UpdateDocumentFileParamsMode1TypedDict",
    "UpdateDocumentFileParamsModeStatic",
    "UpdateDocumentFileParamsModeTypedDict",
    "UpdateDocumentFileParamsModeVideo",
    "UpdateDocumentFileParamsTypedDict",
    "UpdateDocumentFileRequest",
    "UpdateDocumentFileRequestTypedDict",
    "UpdateDocumentFromURLParams",
    "UpdateDocumentFromURLParamsMode",
    "UpdateDocumentFromURLParamsMode1",
    "UpdateDocumentFromURLParamsModeTypedDict",
    "UpdateDocumentFromURLParamsTypedDict",
    "UpdateDocumentFromURLRequest",
    "UpdateDocumentFromURLRequestTypedDict",
    "UpdateDocumentRawParams",
    "UpdateDocumentRawParamsData",
    "UpdateDocumentRawParamsDataTypedDict",
    "UpdateDocumentRawParamsTypedDict",
    "UpdateDocumentRawRequest",
    "UpdateDocumentRawRequestTypedDict",
    "UpdateInstructionParams",
    "UpdateInstructionParamsTypedDict",
    "UpdateInstructionRequest",
    "UpdateInstructionRequestTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "Video",
    "VideoModalityData",
    "VideoModalityDataTypedDict",
    "WordTimestamp",
    "WordTimestampTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AudioModalityData": ".audiomodalitydata",
    "AudioModalityDataTypedDict": ".audiomodalitydata",
    "Connection": ".connection",
    "ConnectionMetadata": ".connection",
    "ConnectionMetadataTypedDict": ".connection",
    "ConnectionTypedDict": ".connection",
    "DisabledBySystemReason": ".connection",
    "Source": ".connection",
    "SourceTypedDict": ".connection",
    "ConnectionBase": ".connectionbase",
    "ConnectionBaseMetadata": ".connectionbase",
    "ConnectionBaseMetadataTypedDict": ".connectionbase",
    "ConnectionBaseTypedDict": ".connectionbase",
    "PartitionStrategy": ".connectionbase",
    "PartitionStrategy1": ".connectionbase",
    "PartitionStrategyTypedDict": ".connectionbase",
    "ConnectionLimitExceededWebhook": ".connectionlimitexceededwebhook",
    "ConnectionLimitExceededWebhookTypedDict": ".connectionlimitexceededwebhook",
    "ConnectionLimitExceededWebhookPayload": ".connectionlimitexceededwebhookpayload",
    "ConnectionLimitExceededWebhookPayloadTypedDict": ".connectionlimitexceededwebhookpayload",
    "ConnectionLimitParams": ".connectionlimitparams",
    "ConnectionLimitParamsTypedDict": ".connectionlimitparams",
    "ConnectionList": ".connectionlist",
    "ConnectionListTypedDict": ".connectionlist",
    "ConnectionStats": ".connectionstats",
    "ConnectionStatsTypedDict": ".connectionstats",
    "ConnectionSyncFinishedWebhook": ".connectionsyncfinishedwebhook",
    "ConnectionSyncFinishedWebhookTypedDict": ".connectionsyncfinishedwebhook",
    "ConnectionSyncFinishedWebhookPayload": ".connectionsyncfinishedwebhookpayload",
    "ConnectionSyncFinishedWebhookPayloadTypedDict": ".connectionsyncfinishedwebhookpayload",
    "ConnectionSyncProgressWebhook": ".connectionsyncprogresswebhook",
    "ConnectionSyncProgressWebhookTypedDict": ".connectionsyncprogresswebhook",
    "ConnectionSyncProgressWebhookPayload": ".connectionsyncprogresswebhookpayload",
    "ConnectionSyncProgressWebhookPayloadTypedDict": ".connectionsyncprogresswebhookpayload",
    "ConnectionSyncStartedWebhook": ".connectionsyncstartedwebhook",
    "ConnectionSyncStartedWebhookTypedDict": ".connectionsyncstartedwebhook",
    "ConnectionSyncStartedWebhookPayload": ".connectionsyncstartedwebhookpayload",
    "ConnectionSyncStartedWebhookPayloadTypedDict": ".connectionsyncstartedwebhookpayload",
    "ConnectorSource": ".connectorsource",
    "ConnectorSourceTypeInfo": ".connectorsourcetypeinfo",
    "ConnectorSourceTypeInfoTypedDict": ".connectorsourcetypeinfo",
    "CreateDocumentFromURLParams": ".createdocumentfromurlparams",
    "CreateDocumentFromURLParamsMetadata": ".createdocumentfromurlparams",
    "CreateDocumentFromURLParamsMetadataTypedDict": ".createdocumentfromurlparams",
    "CreateDocumentFromURLParamsMode": ".createdocumentfromurlparams",
    "CreateDocumentFromURLParamsModeTypedDict": ".createdocumentfromurlparams",
    "CreateDocumentFromURLParamsTypedDict": ".createdocumentfromurlparams",
    "Mode1": ".createdocumentfromurlparams",
    "CreateDocumentParams": ".createdocumentparams",
    "CreateDocumentParamsTypedDict": ".createdocumentparams",
    "File": ".createdocumentparams",
    "FileTypedDict": ".createdocumentparams",
    "Metadata": ".createdocumentparams",
    "MetadataTypedDict": ".createdocumentparams",
    "Mode": ".createdocumentparams",
    "ModeStatic": ".createdocumentparams",
    "ModeTypedDict": ".createdocumentparams",
    "ModeVideo": ".createdocumentparams",
    "One": ".createdocumentparams",
    "One1": ".createdocumentparams",
    "One2": ".createdocumentparams",
    "One2TypedDict": ".createdocumentparams",
    "OneTypedDict": ".createdocumentparams",
    "Two": ".createdocumentparams",
    "TwoTypedDict": ".createdocumentparams",
    "CreateDocumentRawParams": ".createdocumentrawparams",
    "CreateDocumentRawParamsMetadata": ".createdocumentrawparams",
    "CreateDocumentRawParamsMetadataTypedDict": ".createdocumentrawparams",
    "CreateDocumentRawParamsTypedDict": ".createdocumentrawparams",
    "Data": ".createdocumentrawparams",
    "DataTypedDict": ".createdocumentrawparams",
    "CreateInstructionParams": ".createinstructionparams",
    "CreateInstructionParamsScope": ".createinstructionparams",
    "CreateInstructionParamsTypedDict": ".createinstructionparams",
    "CreatePartitionParams": ".createpartitionparams",
    "CreatePartitionParamsTypedDict": ".createpartitionparams",
    "DeleteConnectionConnectionsConnectionIDDeletePostRequest": ".delete_connection_connections_connection_id_delete_postop",
    "DeleteConnectionConnectionsConnectionIDDeletePostRequestTypedDict": ".delete_connection_connections_connection_id_delete_postop",
    "DeletePartitionPartitionsPartitionIDDeleteRequest": ".delete_partition_partitions_partition_id_deleteop",
    "DeletePartitionPartitionsPartitionIDDeleteRequestTypedDict": ".delete_partition_partitions_partition_id_deleteop",
    "DeleteConnectionPayload": ".deleteconnectionpayload",
    "DeleteConnectionPayloadTypedDict": ".deleteconnectionpayload",
    "DeleteDocumentRequest": ".deletedocumentop",
    "DeleteDocumentRequestTypedDict": ".deletedocumentop",
    "DeleteInstructionRequest": ".deleteinstructionop",
    "DeleteInstructionRequestTypedDict": ".deleteinstructionop",
    "Document": ".document",
    "DocumentMetadata": ".document",
    "DocumentMetadataTypedDict": ".document",
    "DocumentTypedDict": ".document",
    "DocumentChunk": ".documentchunk",
    "DocumentChunkTypedDict": ".documentchunk",
    "DocumentChunkDetail": ".documentchunkdetail",
    "DocumentChunkDetailTypedDict": ".documentchunkdetail",
    "ModalityData": ".documentchunkdetail",
    "ModalityDataTypedDict": ".documentchunkdetail",
    "DocumentChunkList": ".documentchunklist",
    "DocumentChunkListTypedDict": ".documentchunklist",
    "DocumentDelete": ".documentdelete",
    "DocumentDeleteTypedDict": ".documentdelete",
    "DocumentDeleteWebhook": ".documentdeletewebhook",
    "DocumentDeleteWebhookTypedDict": ".documentdeletewebhook",
    "DocumentDeleteWebhookPayload": ".documentdeletewebhookpayload",
    "DocumentDeleteWebhookPayloadTypedDict": ".documentdeletewebhookpayload",
    "DocumentFileUpdate": ".documentfileupdate",
    "DocumentFileUpdateTypedDict": ".documentfileupdate",
    "DocumentGet": ".documentget",
    "DocumentGetMetadata": ".documentget",
    "DocumentGetMetadataTypedDict": ".documentget",
    "DocumentGetTypedDict": ".documentget",
    "DocumentList": ".documentlist",
    "DocumentListTypedDict": ".documentlist",
    "DocumentMetadataUpdate": ".documentmetadataupdate",
    "DocumentMetadataUpdateMetadata": ".documentmetadataupdate",
    "DocumentMetadataUpdateMetadataTypedDict": ".documentmetadataupdate",
    "DocumentMetadataUpdateTypedDict": ".documentmetadataupdate",
    "DocumentRawUpdate": ".documentrawupdate",
    "DocumentRawUpdateTypedDict": ".documentrawupdate",
    "DocumentSummary": ".documentsummary",
    "DocumentSummaryTypedDict": ".documentsummary",
    "DocumentUpdateWebhook": ".documentupdatewebhook",
    "DocumentUpdateWebhookTypedDict": ".documentupdatewebhook",
    "DocumentUpdateWebhookPayload": ".documentupdatewebhookpayload",
    "DocumentUpdateWebhookPayloadTypedDict": ".documentupdatewebhookpayload",
    "DocumentURLUpdate": ".documenturlupdate",
    "DocumentURLUpdateTypedDict": ".documenturlupdate",
    "DocumentWithContent": ".documentwithcontent",
    "DocumentWithContentMetadata": ".documentwithcontent",
    "DocumentWithContentMetadataTypedDict": ".documentwithcontent",
    "DocumentWithContentTypedDict": ".documentwithcontent",
    "Entity": ".entity",
    "EntityTypedDict": ".entity",
    "EntityExtractedWebhook": ".entityextractedwebhook",
    "EntityExtractedWebhookTypedDict": ".entityextractedwebhook",
    "EntityExtractedWebhookPayload": ".entityextractedwebhookpayload",
    "EntityExtractedWebhookPayloadTypedDict": ".entityextractedwebhookpayload",
    "EntityList": ".entitylist",
    "EntityListTypedDict": ".entitylist",
    "ErrorMessage": ".errormessage",
    "ErrorMessageData": ".errormessage",
    "EventeventPostBody": ".eventevent_postop",
    "EventeventPostBodyTypedDict": ".eventevent_postop",
    "GetConnectionConnectionsConnectionIDGetRequest": ".get_connection_connections_connection_id_getop",
    "GetConnectionConnectionsConnectionIDGetRequestTypedDict": ".get_connection_connections_connection_id_getop",
    "GetConnectionStatsConnectionsConnectionIDStatsGetRequest": ".get_connection_stats_connections_connection_id_stats_getop",
    "GetConnectionStatsConnectionsConnectionIDStatsGetRequestTypedDict": ".get_connection_stats_connections_connection_id_stats_getop",
    "GetPartitionPartitionsPartitionIDGetRequest": ".get_partition_partitions_partition_id_getop",
    "GetPartitionPartitionsPartitionIDGetRequestTypedDict": ".get_partition_partitions_partition_id_getop",
    "GetDocumentChunkContentRequest": ".getdocumentchunkcontentop",
    "GetDocumentChunkContentRequestTypedDict": ".getdocumentchunkcontentop",
    "MediaType": ".getdocumentchunkcontentop",
    "GetDocumentChunkRequest": ".getdocumentchunkop",
    "GetDocumentChunkRequestTypedDict": ".getdocumentchunkop",
    "GetDocumentChunksRequest": ".getdocumentchunksop",
    "GetDocumentChunksRequestTypedDict": ".getdocumentchunksop",
    "GetDocumentContentRequest": ".getdocumentcontentop",
    "GetDocumentContentRequestTypedDict": ".getdocumentcontentop",
    "QueryParam1": ".getdocumentcontentop",
    "QueryParamMediaType": ".getdocumentcontentop",
    "QueryParamMediaTypeTypedDict": ".getdocumentcontentop",
    "GetDocumentRequest": ".getdocumentop",
    "GetDocumentRequestTypedDict": ".getdocumentop",
    "GetDocumentSourceRequest": ".getdocumentsourceop",
    "GetDocumentSourceRequestTypedDict": ".getdocumentsourceop",
    "GetDocumentSummaryRequest": ".getdocumentsummaryop",
    "GetDocumentSummaryRequestTypedDict": ".getdocumentsummaryop",
    "HTTPValidationError": ".httpvalidationerror",
    "HTTPValidationErrorData": ".httpvalidationerror",
    "Instruction": ".instruction",
    "InstructionTypedDict": ".instruction",
    "Scope": ".instruction",
    "Link": ".link",
    "LinkTypedDict": ".link",
    "ListConnectionsConnectionsGetRequest": ".list_connections_connections_getop",
    "ListConnectionsConnectionsGetRequestTypedDict": ".list_connections_connections_getop",
    "ListConnectionsConnectionsGetResponse": ".list_connections_connections_getop",
    "ListConnectionsConnectionsGetResponseTypedDict": ".list_connections_connections_getop",
    "ListPartitionsPartitionsGetRequest": ".list_partitions_partitions_getop",
    "ListPartitionsPartitionsGetRequestTypedDict": ".list_partitions_partitions_getop",
    "ListPartitionsPartitionsGetResponse": ".list_partitions_partitions_getop",
    "ListPartitionsPartitionsGetResponseTypedDict": ".list_partitions_partitions_getop",
    "ListConnectorSourceTypeInfo": ".listconnectorsourcetypeinfo",
    "ListConnectorSourceTypeInfoTypedDict": ".listconnectorsourcetypeinfo",
    "ListDocumentsRequest": ".listdocumentsop",
    "ListDocumentsRequestTypedDict": ".listdocumentsop",
    "ListDocumentsResponse": ".listdocumentsop",
    "ListDocumentsResponseTypedDict": ".listdocumentsop",
    "ListEntitiesByDocumentRequest": ".listentitiesbydocumentop",
    "ListEntitiesByDocumentRequestTypedDict": ".listentitiesbydocumentop",
    "ListEntitiesByDocumentResponse": ".listentitiesbydocumentop",
    "ListEntitiesByDocumentResponseTypedDict": ".listentitiesbydocumentop",
    "ListEntitiesByInstructionRequest": ".listentitiesbyinstructionop",
    "ListEntitiesByInstructionRequestTypedDict": ".listentitiesbyinstructionop",
    "ListEntitiesByInstructionResponse": ".listentitiesbyinstructionop",
    "ListEntitiesByInstructionResponseTypedDict": ".listentitiesbyinstructionop",
    "MediaModeParam": ".mediamodeparam",
    "MediaModeParamTypedDict": ".mediamodeparam",
    "Static": ".mediamodeparam",
    "Video": ".mediamodeparam",
    "OAuthURLCreate": ".oauthurlcreate",
    "OAuthURLCreateMetadata": ".oauthurlcreate",
    "OAuthURLCreateMetadataTypedDict": ".oauthurlcreate",
    "OAuthURLCreateMode": ".oauthurlcreate",
    "OAuthURLCreateMode1": ".oauthurlcreate",
    "OAuthURLCreateModeTypedDict": ".oauthurlcreate",
    "OAuthURLCreateTypedDict": ".oauthurlcreate",
    "Theme": ".oauthurlcreate",
    "OAuthURLResponse": ".oauthurlresponse",
    "OAuthURLResponseTypedDict": ".oauthurlresponse",
    "Pagination": ".pagination",
    "PaginationTypedDict": ".pagination",
    "Partition": ".partition",
    "PartitionTypedDict": ".partition",
    "PartitionDetail": ".partitiondetail",
    "PartitionDetailTypedDict": ".partitiondetail",
    "PartitionLimitExceededWebhook": ".partitionlimitexceededwebhook",
    "PartitionLimitExceededWebhookTypedDict": ".partitionlimitexceededwebhook",
    "LimitType": ".partitionlimitexceededwebhookpayload",
    "PartitionLimitExceededWebhookPayload": ".partitionlimitexceededwebhookpayload",
    "PartitionLimitExceededWebhookPayloadTypedDict": ".partitionlimitexceededwebhookpayload",
    "PartitionLimitParams": ".partitionlimitparams",
    "PartitionLimitParamsTypedDict": ".partitionlimitparams",
    "PartitionLimits": ".partitionlimits",
    "PartitionLimitsTypedDict": ".partitionlimits",
    "PartitionList": ".partitionlist",
    "PartitionListTypedDict": ".partitionlist",
    "PartitionStats": ".partitionstats",
    "PartitionStatsTypedDict": ".partitionstats",
    "PatchDocumentMetadataRequest": ".patchdocumentmetadataop",
    "PatchDocumentMetadataRequestTypedDict": ".patchdocumentmetadataop",
    "PatchDocumentMetadataParams": ".patchdocumentmetadataparams",
    "PatchDocumentMetadataParamsTypedDict": ".patchdocumentmetadataparams",
    "ResponseOK": ".responseok",
    "ResponseOKTypedDict": ".responseok",
    "Retrieval": ".retrieval",
    "RetrievalTypedDict": ".retrieval",
    "RetrieveParams": ".retrieveparams",
    "RetrieveParamsTypedDict": ".retrieveparams",
    "ScoredChunk": ".scoredchunk",
    "ScoredChunkTypedDict": ".scoredchunk",
    "SDKError": ".sdkerror",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SetConnectionEnabledConnectionsConnectionIDEnabledPutRequest": ".set_connection_enabled_connections_connection_id_enabled_putop",
    "SetConnectionEnabledConnectionsConnectionIDEnabledPutRequestTypedDict": ".set_connection_enabled_connections_connection_id_enabled_putop",
    "SetConnectionLimitsConnectionsConnectionIDLimitPutRequest": ".set_connection_limits_connections_connection_id_limit_putop",
    "SetConnectionLimitsConnectionsConnectionIDLimitPutRequestTypedDict": ".set_connection_limits_connections_connection_id_limit_putop",
    "SetPartitionLimitsPartitionsPartitionIDLimitsPutRequest": ".set_partition_limits_partitions_partition_id_limits_putop",
    "SetPartitionLimitsPartitionsPartitionIDLimitsPutRequestTypedDict": ".set_partition_limits_partitions_partition_id_limits_putop",
    "Reason": ".setconnectionenabledpayload",
    "SetConnectionEnabledPayload": ".setconnectionenabledpayload",
    "SetConnectionEnabledPayloadTypedDict": ".setconnectionenabledpayload",
    "SyncConnectionRequest": ".syncconnectionop",
    "SyncConnectionRequestTypedDict": ".syncconnectionop",
    "UpdateConnectionConnectionsConnectionIDPutRequest": ".update_connection_connections_connection_id_putop",
    "UpdateConnectionConnectionsConnectionIDPutRequestTypedDict": ".update_connection_connections_connection_id_putop",
    "UpdateDocumentFileRequest": ".updatedocumentfileop",
    "UpdateDocumentFileRequestTypedDict": ".updatedocumentfileop",
    "Mode2": ".updatedocumentfileparams",
    "Mode2TypedDict": ".updatedocumentfileparams",
    "UpdateDocumentFileParams": ".updatedocumentfileparams",
    "UpdateDocumentFileParams11": ".updatedocumentfileparams",
    "UpdateDocumentFileParams12": ".updatedocumentfileparams",
    "UpdateDocumentFileParams12TypedDict": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsFile": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsFileTypedDict": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsMode": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsMode1": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsMode1TypedDict": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsModeStatic": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsModeTypedDict": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsModeVideo": ".updatedocumentfileparams",
    "UpdateDocumentFileParamsTypedDict": ".updatedocumentfileparams",
    "UpdateDocumentFromURLRequest": ".updatedocumentfromurlop",
    "UpdateDocumentFromURLRequestTypedDict": ".updatedocumentfromurlop",
    "UpdateDocumentFromURLParams": ".updatedocumentfromurlparams",
    "UpdateDocumentFromURLParamsMode": ".updatedocumentfromurlparams",
    "UpdateDocumentFromURLParamsMode1": ".updatedocumentfromurlparams",
    "UpdateDocumentFromURLParamsModeTypedDict": ".updatedocumentfromurlparams",
    "UpdateDocumentFromURLParamsTypedDict": ".updatedocumentfromurlparams",
    "UpdateDocumentRawRequest": ".updatedocumentrawop",
    "UpdateDocumentRawRequestTypedDict": ".updatedocumentrawop",
    "UpdateDocumentRawParams": ".updatedocumentrawparams",
    "UpdateDocumentRawParamsData": ".updatedocumentrawparams",
    "UpdateDocumentRawParamsDataTypedDict": ".updatedocumentrawparams",
    "UpdateDocumentRawParamsTypedDict": ".updatedocumentrawparams",
    "UpdateInstructionRequest": ".updateinstructionop",
    "UpdateInstructionRequestTypedDict": ".updateinstructionop",
    "UpdateInstructionParams": ".updateinstructionparams",
    "UpdateInstructionParamsTypedDict": ".updateinstructionparams",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "VideoModalityData": ".videomodalitydata",
    "VideoModalityDataTypedDict": ".videomodalitydata",
    "WordTimestamp": ".wordtimestamp",
    "WordTimestampTypedDict": ".wordtimestamp",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)
