"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apielement import APIElement, APIElementTypedDict
from .boundingboxlocation import BoundingBoxLocation, BoundingBoxLocationTypedDict
from .characterindexlocation import (
    CharacterIndexLocation,
    CharacterIndexLocationTypedDict,
)
from .documentelementtype import DocumentElementType
from .durationlocation import DurationLocation, DurationLocationTypedDict
from .spreadsheetlocation import SpreadsheetLocation, SpreadsheetLocationTypedDict
from datetime import datetime
from pydantic import Discriminator, Tag, model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from ragie.utils import get_discriminator
from typing import Any, Dict, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


LocationTypedDict = TypeAliasType(
    "LocationTypedDict",
    Union[
        CharacterIndexLocationTypedDict,
        SpreadsheetLocationTypedDict,
        DurationLocationTypedDict,
        BoundingBoxLocationTypedDict,
    ],
)


Location = Annotated[
    Union[
        Annotated[BoundingBoxLocation, Tag("bounding_box")],
        Annotated[CharacterIndexLocation, Tag("character_index")],
        Annotated[DurationLocation, Tag("duration")],
        Annotated[SpreadsheetLocation, Tag("spreadsheet")],
    ],
    Discriminator(lambda m: get_discriminator(m, "location_type", "location_type")),
]


class APIDocumentElementTypedDict(TypedDict):
    id: str
    created_at: datetime
    index: int
    metadata: Dict[str, Any]
    type: DocumentElementType
    text: Nullable[str]
    markdown: Nullable[str]
    data: APIElementTypedDict
    location: NotRequired[Nullable[LocationTypedDict]]


class APIDocumentElement(BaseModel):
    id: str

    created_at: datetime

    index: int

    metadata: Dict[str, Any]

    type: DocumentElementType

    text: Nullable[str]

    markdown: Nullable[str]

    data: APIElement

    location: OptionalNullable[Location] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["location"])
        nullable_fields = set(["text", "markdown", "location"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
