"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .wordtimestamp import WordTimestamp, WordTimestampTypedDict
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AudioModalityDataTypedDict(TypedDict):
    type: Literal["audio"]
    word_timestamps: NotRequired[List[WordTimestampTypedDict]]


class AudioModalityData(BaseModel):
    TYPE: Annotated[
        Annotated[Optional[Literal["audio"]], AfterValidator(validate_const("audio"))],
        pydantic.Field(alias="type"),
    ] = "audio"

    word_timestamps: Optional[List[WordTimestamp]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "word_timestamps"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AudioModalityData.model_rebuild()
except NameError:
    pass
