"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .oauthrefreshtokencredentials import (
    OAuthRefreshTokenCredentials,
    OAuthRefreshTokenCredentialsTypedDict,
)
from .sharepointdata import SharepointData, SharepointDataTypedDict
import pydantic
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel
from ragie.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class AuthenticatorSharepointConnectionTypedDict(TypedDict):
    data: SharepointDataTypedDict
    user_email: str
    r"""The email of the Sharepoint account this is for"""
    credentials: OAuthRefreshTokenCredentialsTypedDict
    provider: Literal["sharepoint"]


class AuthenticatorSharepointConnection(BaseModel):
    data: SharepointData

    user_email: str
    r"""The email of the Sharepoint account this is for"""

    credentials: OAuthRefreshTokenCredentials

    PROVIDER: Annotated[
        Annotated[Literal["sharepoint"], AfterValidator(validate_const("sharepoint"))],
        pydantic.Field(alias="provider"),
    ] = "sharepoint"
