"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class BoundingBoxLocationTypedDict(TypedDict):
    r"""Location within a paginated document using normalized coordinates."""

    left: float
    r"""Left coordinate (0.0 to 1.0)"""
    top: float
    r"""Top coordinate (0.0 to 1.0)"""
    width: float
    r"""Width of the element (0.0 to 1.0)"""
    height: float
    r"""Height of the element (0.0 to 1.0)"""
    page_number: int
    r"""Page number"""
    location_type: Literal["bounding_box"]


class BoundingBoxLocation(BaseModel):
    r"""Location within a paginated document using normalized coordinates."""

    left: float
    r"""Left coordinate (0.0 to 1.0)"""

    top: float
    r"""Top coordinate (0.0 to 1.0)"""

    width: float
    r"""Width of the element (0.0 to 1.0)"""

    height: float
    r"""Height of the element (0.0 to 1.0)"""

    page_number: int
    r"""Page number"""

    LOCATION_TYPE: Annotated[
        Annotated[
            Optional[Literal["bounding_box"]],
            AfterValidator(validate_const("bounding_box")),
        ],
        pydantic.Field(alias="location_type"),
    ] = "bounding_box"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["location_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    BoundingBoxLocation.model_rebuild()
except NameError:
    pass
