"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class CharacterIndexLocationTypedDict(TypedDict):
    r"""Location within linear text using zero-based character offsets."""

    start_char_index: int
    r"""Start character index (inclusive)"""
    end_char_index: int
    r"""End character index (exclusive)"""
    location_type: Literal["character_index"]


class CharacterIndexLocation(BaseModel):
    r"""Location within linear text using zero-based character offsets."""

    start_char_index: int
    r"""Start character index (inclusive)"""

    end_char_index: int
    r"""End character index (exclusive)"""

    LOCATION_TYPE: Annotated[
        Annotated[
            Optional[Literal["character_index"]],
            AfterValidator(validate_const("character_index")),
        ],
        pydantic.Field(alias="location_type"),
    ] = "character_index"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["location_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CharacterIndexLocation.model_rebuild()
except NameError:
    pass
