"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CodeStepTypedDict(TypedDict):
    think: str
    current_question: str
    code_issue: str
    r"""The natural language description of the code issue you need to solve."""
    type: Literal["code"]
    errored: NotRequired[bool]
    code: NotRequired[str]
    r"""The code you generated to solve the code issue."""
    code_result: NotRequired[str]
    r"""The result of the code you generated after executing it."""


class CodeStep(BaseModel):
    think: str

    current_question: str

    code_issue: str
    r"""The natural language description of the code issue you need to solve."""

    TYPE: Annotated[
        Annotated[Optional[Literal["code"]], AfterValidator(validate_const("code"))],
        pydantic.Field(alias="type"),
    ] = "code"

    errored: Optional[bool] = False

    code: Optional[str] = ""
    r"""The code you generated to solve the code issue."""

    code_result: Optional[str] = ""
    r"""The result of the code you generated after executing it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "errored", "code", "code_result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CodeStep.model_rebuild()
except NameError:
    pass
