"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectionsyncstartedwebhookpayload import (
    ConnectionSyncStartedWebhookPayload,
    ConnectionSyncStartedWebhookPayloadTypedDict,
)
from enum import Enum
import pydantic
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel
from ragie.utils import validate_const
from typing_extensions import Annotated, TypedDict


class ConnectionSyncStartedWebhookType(str, Enum):
    CONNECTION_SYNC_STARTED = "connection_sync_started"


class ConnectionSyncStartedWebhookTypedDict(TypedDict):
    nonce: str
    payload: ConnectionSyncStartedWebhookPayloadTypedDict
    type: ConnectionSyncStartedWebhookType


class ConnectionSyncStartedWebhook(BaseModel):
    nonce: str

    payload: ConnectionSyncStartedWebhookPayload

    TYPE: Annotated[
        Annotated[
            ConnectionSyncStartedWebhookType,
            AfterValidator(
                validate_const(ConnectionSyncStartedWebhookType.CONNECTION_SYNC_STARTED)
            ),
        ],
        pydantic.Field(alias="type"),
    ] = ConnectionSyncStartedWebhookType.CONNECTION_SYNC_STARTED
