"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectionsyncprogresswebhookpayload import (
    ConnectionSyncProgressWebhookPayload,
    ConnectionSyncProgressWebhookPayloadTypedDict,
)
import pydantic
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel
from ragie.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ConnectionSyncProgressWebhookTypedDict(TypedDict):
    nonce: str
    payload: ConnectionSyncProgressWebhookPayloadTypedDict
    type: Literal["connection_sync_progress"]


class ConnectionSyncProgressWebhook(BaseModel):
    nonce: str

    payload: ConnectionSyncProgressWebhookPayload

    TYPE: Annotated[
        Annotated[
            Literal["connection_sync_progress"],
            AfterValidator(validate_const("connection_sync_progress")),
        ],
        pydantic.Field(alias="type"),
    ] = "connection_sync_progress"
