"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authenticatorconfluenceconnection import (
    AuthenticatorConfluenceConnection,
    AuthenticatorConfluenceConnectionTypedDict,
)
from .authenticatordropboxconnection import (
    AuthenticatorDropboxConnection,
    AuthenticatorDropboxConnectionTypedDict,
)
from .authenticatorgmailconnection import (
    AuthenticatorGmailConnection,
    AuthenticatorGmailConnectionTypedDict,
)
from .authenticatorgoogledriveconnection import (
    AuthenticatorGoogleDriveConnection,
    AuthenticatorGoogleDriveConnectionTypedDict,
)
from .authenticatorhubspotconnection import (
    AuthenticatorHubspotConnection,
    AuthenticatorHubspotConnectionTypedDict,
)
from .authenticatorjiraconnection import (
    AuthenticatorJiraConnection,
    AuthenticatorJiraConnectionTypedDict,
)
from .authenticatornotionconnection import (
    AuthenticatorNotionConnection,
    AuthenticatorNotionConnectionTypedDict,
)
from .authenticatoronedriveconnection import (
    AuthenticatorOnedriveConnection,
    AuthenticatorOnedriveConnectionTypedDict,
)
from .authenticatorsalesforceconnection import (
    AuthenticatorSalesforceConnection,
    AuthenticatorSalesforceConnectionTypedDict,
)
from .authenticatorsharepointconnection import (
    AuthenticatorSharepointConnection,
    AuthenticatorSharepointConnectionTypedDict,
)
from .authenticatorslackconnection import (
    AuthenticatorSlackConnection,
    AuthenticatorSlackConnectionTypedDict,
)
from .mediamodeparam import MediaModeParam, MediaModeParamTypedDict
from pydantic import Field, model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


CreateAuthenticatorConnectionMetadataTypedDict = TypeAliasType(
    "CreateAuthenticatorConnectionMetadataTypedDict",
    Union[str, int, float, bool, List[str]],
)


CreateAuthenticatorConnectionMetadata = TypeAliasType(
    "CreateAuthenticatorConnectionMetadata", Union[str, int, float, bool, List[str]]
)


CreateAuthenticatorConnectionConnectionTypedDict = TypeAliasType(
    "CreateAuthenticatorConnectionConnectionTypedDict",
    Union[
        AuthenticatorJiraConnectionTypedDict,
        AuthenticatorConfluenceConnectionTypedDict,
        AuthenticatorDropboxConnectionTypedDict,
        AuthenticatorGoogleDriveConnectionTypedDict,
        AuthenticatorGmailConnectionTypedDict,
        AuthenticatorOnedriveConnectionTypedDict,
        AuthenticatorSalesforceConnectionTypedDict,
        AuthenticatorSharepointConnectionTypedDict,
        AuthenticatorSlackConnectionTypedDict,
        AuthenticatorHubspotConnectionTypedDict,
        AuthenticatorNotionConnectionTypedDict,
    ],
)


CreateAuthenticatorConnectionConnection = Annotated[
    Union[
        AuthenticatorConfluenceConnection,
        AuthenticatorDropboxConnection,
        AuthenticatorGmailConnection,
        AuthenticatorGoogleDriveConnection,
        AuthenticatorHubspotConnection,
        AuthenticatorJiraConnection,
        AuthenticatorNotionConnection,
        AuthenticatorOnedriveConnection,
        AuthenticatorSalesforceConnection,
        AuthenticatorSharepointConnection,
        AuthenticatorSlackConnection,
    ],
    Field(discriminator="PROVIDER"),
]


class CreateAuthenticatorConnectionTypedDict(TypedDict):
    partition_strategy: MediaModeParamTypedDict
    connection: CreateAuthenticatorConnectionConnectionTypedDict
    partition: NotRequired[Nullable[str]]
    page_limit: NotRequired[Nullable[int]]
    config: NotRequired[Nullable[Dict[str, Any]]]
    metadata: NotRequired[Dict[str, CreateAuthenticatorConnectionMetadataTypedDict]]
    r"""Metadata for the document. Keys must be strings. Values may be strings, numbers, booleans, or lists of strings. Numbers may be integers or floating point and will be converted to 64 bit floating point. 1000 total values are allowed. Each item in an array counts towards the total. The following keys are reserved for internal use: `document_id`, `document_type`, `document_source`, `document_name`, `document_uploaded_at`, `start_time`, `end_time`, `chunk_content_type`."""


class CreateAuthenticatorConnection(BaseModel):
    partition_strategy: MediaModeParam

    connection: CreateAuthenticatorConnectionConnection

    partition: OptionalNullable[str] = UNSET

    page_limit: OptionalNullable[int] = UNSET

    config: OptionalNullable[Dict[str, Any]] = UNSET

    metadata: Optional[Dict[str, CreateAuthenticatorConnectionMetadata]] = None
    r"""Metadata for the document. Keys must be strings. Values may be strings, numbers, booleans, or lists of strings. Numbers may be integers or floating point and will be converted to 64 bit floating point. 1000 total values are allowed. Each item in an array counts towards the total. The following keys are reserved for internal use: `document_id`, `document_type`, `document_source`, `document_name`, `document_uploaded_at`, `start_time`, `end_time`, `chunk_content_type`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["partition", "page_limit", "config", "metadata"])
        nullable_fields = set(["partition", "page_limit", "config"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
