"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import NotRequired, TypedDict


class CreatePartitionParamsTypedDict(TypedDict):
    name: str
    pages_hosted_limit_monthly: NotRequired[Nullable[int]]
    pages_processed_limit_monthly: NotRequired[Nullable[int]]
    pages_hosted_limit_max: NotRequired[Nullable[int]]
    pages_processed_limit_max: NotRequired[Nullable[int]]


class CreatePartitionParams(BaseModel):
    name: str

    pages_hosted_limit_monthly: OptionalNullable[int] = UNSET

    pages_processed_limit_monthly: OptionalNullable[int] = UNSET

    pages_hosted_limit_max: OptionalNullable[int] = UNSET

    pages_processed_limit_max: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "pages_hosted_limit_monthly",
            "pages_processed_limit_monthly",
            "pages_hosted_limit_max",
            "pages_processed_limit_max",
        ]
        nullable_fields = [
            "pages_hosted_limit_monthly",
            "pages_processed_limit_monthly",
            "pages_hosted_limit_max",
            "pages_processed_limit_max",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
