"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .oauthcredentials import OAuthCredentials, OAuthCredentialsTypedDict


CreateAuthenticatorPayloadTypedDict = OAuthCredentialsTypedDict


CreateAuthenticatorPayload = OAuthCredentials
