"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Dict, List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


DocumentWithContentMetadataTypedDict = TypeAliasType(
    "DocumentWithContentMetadataTypedDict", Union[str, int, float, bool, List[str]]
)


DocumentWithContentMetadata = TypeAliasType(
    "DocumentWithContentMetadata", Union[str, int, float, bool, List[str]]
)


class DocumentWithContentTypedDict(TypedDict):
    status: str
    id: str
    created_at: datetime
    updated_at: datetime
    name: str
    metadata: Dict[str, DocumentWithContentMetadataTypedDict]
    partition: str
    content: str
    chunk_count: NotRequired[Nullable[int]]
    external_id: NotRequired[Nullable[str]]
    page_count: NotRequired[Nullable[float]]


class DocumentWithContent(BaseModel):
    status: str

    id: str

    created_at: datetime

    updated_at: datetime

    name: str

    metadata: Dict[str, DocumentWithContentMetadata]

    partition: str

    content: str

    chunk_count: OptionalNullable[int] = UNSET

    external_id: OptionalNullable[str] = UNSET

    page_count: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["chunk_count", "external_id", "page_count"])
        nullable_fields = set(["chunk_count", "external_id", "page_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
