"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .documentdeletewebhookpayload import (
    DocumentDeleteWebhookPayload,
    DocumentDeleteWebhookPayloadTypedDict,
)
import pydantic
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel
from ragie.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class DocumentDeleteWebhookTypedDict(TypedDict):
    nonce: str
    payload: DocumentDeleteWebhookPayloadTypedDict
    type: Literal["document_deleted"]


class DocumentDeleteWebhook(BaseModel):
    nonce: str

    payload: DocumentDeleteWebhookPayload

    TYPE: Annotated[
        Annotated[
            Literal["document_deleted"],
            AfterValidator(validate_const("document_deleted")),
        ],
        pydantic.Field(alias="type"),
    ] = "document_deleted"
