"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class EntityTypedDict(TypedDict):
    id: str
    created_at: datetime
    updated_at: datetime
    instruction_id: str
    r"""The ID of the instruction which generated the entity."""
    document_id: str
    r"""The ID of the document which the entity was produced from."""
    data: Dict[str, Any]
    chunk_id: NotRequired[Nullable[str]]
    instruction_schema_version: NotRequired[Nullable[int]]
    r"""Instruction entity schema version used to generate this entity."""
    instruction_schema_shape_fingerprint: NotRequired[Nullable[str]]
    r"""Shape-only fingerprint of the instruction entity schema used to generate this entity."""


class Entity(BaseModel):
    id: str

    created_at: datetime

    updated_at: datetime

    instruction_id: str
    r"""The ID of the instruction which generated the entity."""

    document_id: str
    r"""The ID of the document which the entity was produced from."""

    data: Dict[str, Any]

    chunk_id: OptionalNullable[str] = UNSET

    instruction_schema_version: OptionalNullable[int] = UNSET
    r"""Instruction entity schema version used to generate this entity."""

    instruction_schema_shape_fingerprint: OptionalNullable[str] = UNSET
    r"""Shape-only fingerprint of the instruction entity schema used to generate this entity."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "chunk_id",
                "instruction_schema_version",
                "instruction_schema_shape_fingerprint",
            ]
        )
        nullable_fields = set(
            [
                "chunk_id",
                "instruction_schema_version",
                "instruction_schema_shape_fingerprint",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
