"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectionlimitexceededwebhook import (
    ConnectionLimitExceededWebhook,
    ConnectionLimitExceededWebhookTypedDict,
)
from .connectionsyncfinishedwebhook import (
    ConnectionSyncFinishedWebhook,
    ConnectionSyncFinishedWebhookTypedDict,
)
from .connectionsyncprogresswebhook import (
    ConnectionSyncProgressWebhook,
    ConnectionSyncProgressWebhookTypedDict,
)
from .connectionsyncstartedwebhook import (
    ConnectionSyncStartedWebhook,
    ConnectionSyncStartedWebhookTypedDict,
)
from .documentdeletewebhook import DocumentDeleteWebhook, DocumentDeleteWebhookTypedDict
from .documentupdatewebhook import DocumentUpdateWebhook, DocumentUpdateWebhookTypedDict
from .entityextractedwebhook import (
    EntityExtractedWebhook,
    EntityExtractedWebhookTypedDict,
)
from .partitionlimitexceededwebhook import (
    PartitionLimitExceededWebhook,
    PartitionLimitExceededWebhookTypedDict,
)
from typing import Union
from typing_extensions import TypeAliasType


EventeventPostBodyTypedDict = TypeAliasType(
    "EventeventPostBodyTypedDict",
    Union[
        DocumentUpdateWebhookTypedDict,
        DocumentDeleteWebhookTypedDict,
        EntityExtractedWebhookTypedDict,
        ConnectionSyncStartedWebhookTypedDict,
        ConnectionSyncProgressWebhookTypedDict,
        ConnectionSyncFinishedWebhookTypedDict,
        ConnectionLimitExceededWebhookTypedDict,
        PartitionLimitExceededWebhookTypedDict,
    ],
)


EventeventPostBody = TypeAliasType(
    "EventeventPostBody",
    Union[
        DocumentUpdateWebhook,
        DocumentDeleteWebhook,
        EntityExtractedWebhook,
        ConnectionSyncStartedWebhook,
        ConnectionSyncProgressWebhook,
        ConnectionSyncFinishedWebhook,
        ConnectionLimitExceededWebhook,
        PartitionLimitExceededWebhook,
    ],
)
