"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .formoption import FormOption, FormOptionTypedDict
from enum import Enum
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InputType(str, Enum):
    r"""Type of input."""

    TEXT = "text"
    TEXTAREA = "textarea"
    CHECKBOX = "checkbox"
    RADIO = "radio"
    CHECKBOX_GROUP = "checkbox-group"
    RADIO_GROUP = "radio-group"
    DATE = "date"
    TIME = "time"
    DATE_TIME = "date-time"


class FormFieldTypedDict(TypedDict):
    content: str
    r"""The text content of the form field, including both the label and the value"""
    input_type: InputType
    r"""Type of input."""
    label: str
    r"""The main question/label for the field."""
    type: Literal["FormField"]
    value: NotRequired[Nullable[str]]
    r"""The filled text. For single checkbox: 'true'/'false'."""
    options: NotRequired[Nullable[List[FormOptionTypedDict]]]
    r"""List of available options."""
    selected_values: NotRequired[Nullable[List[str]]]
    r"""The 'label' of the selected option(s)."""
    help_text: NotRequired[Nullable[str]]
    r"""The help text for the form field."""


class FormField(BaseModel):
    content: str
    r"""The text content of the form field, including both the label and the value"""

    input_type: InputType
    r"""Type of input."""

    label: str
    r"""The main question/label for the field."""

    TYPE: Annotated[
        Annotated[
            Optional[Literal["FormField"]], AfterValidator(validate_const("FormField"))
        ],
        pydantic.Field(alias="type"),
    ] = "FormField"

    value: OptionalNullable[str] = UNSET
    r"""The filled text. For single checkbox: 'true'/'false'."""

    options: OptionalNullable[List[FormOption]] = UNSET
    r"""List of available options."""

    selected_values: OptionalNullable[List[str]] = UNSET
    r"""The 'label' of the selected option(s)."""

    help_text: OptionalNullable[str] = UNSET
    r"""The help text for the form field."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["type", "value", "options", "selected_values", "help_text"]
        )
        nullable_fields = set(["value", "options", "selected_values", "help_text"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    FormField.model_rebuild()
except NameError:
    pass
