"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IntercomDataTypedDict(TypedDict):
    articles_help_center: NotRequired[bool]
    admins: NotRequired[bool]
    contacts: NotRequired[bool]
    conversations: NotRequired[bool]
    conversation_attachments: NotRequired[bool]
    conversation_notes: NotRequired[bool]
    tickets: NotRequired[bool]
    ticket_attachments: NotRequired[bool]
    ticket_comments: NotRequired[bool]
    ticket_notes: NotRequired[bool]
    filter_user_id: NotRequired[Nullable[str]]


class IntercomData(BaseModel):
    articles_help_center: Optional[bool] = False

    admins: Optional[bool] = False

    contacts: Optional[bool] = False

    conversations: Optional[bool] = False

    conversation_attachments: Optional[bool] = False

    conversation_notes: Optional[bool] = False

    tickets: Optional[bool] = False

    ticket_attachments: Optional[bool] = False

    ticket_comments: Optional[bool] = False

    ticket_notes: Optional[bool] = False

    filter_user_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "articles_help_center",
                "admins",
                "contacts",
                "conversations",
                "conversation_attachments",
                "conversation_notes",
                "tickets",
                "ticket_attachments",
                "ticket_comments",
                "ticket_notes",
                "filter_user_id",
            ]
        )
        nullable_fields = set(["filter_user_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
