"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LogoTypedDict(TypedDict):
    description: str
    r"""A detailed description of the logo"""
    type: Literal["Logo"]
    content: NotRequired[str]
    r"""The text visible inside the logo (OCR)"""
    base64_data: NotRequired[Nullable[str]]


class Logo(BaseModel):
    description: str
    r"""A detailed description of the logo"""

    TYPE: Annotated[
        Annotated[Optional[Literal["Logo"]], AfterValidator(validate_const("Logo"))],
        pydantic.Field(alias="type"),
    ] = "Logo"

    content: Optional[str] = ""
    r"""The text visible inside the logo (OCR)"""

    base64_data: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "content", "base64_data"])
        nullable_fields = set(["base64_data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Logo.model_rebuild()
except NameError:
    pass
