"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import NotRequired, TypedDict


class Static(str, Enum):
    HI_RES = "hi_res"
    FAST = "fast"
    AGENTIC_OCR = "agentic_ocr"


class Video(str, Enum):
    AUDIO_ONLY = "audio_only"
    VIDEO_ONLY = "video_only"
    AUDIO_VIDEO = "audio_video"


class MediaModeParamTypedDict(TypedDict):
    static: NotRequired[Nullable[Static]]
    audio: NotRequired[Nullable[bool]]
    video: NotRequired[Nullable[Video]]


class MediaModeParam(BaseModel):
    static: OptionalNullable[Static] = UNSET

    audio: OptionalNullable[bool] = UNSET

    video: OptionalNullable[Video] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["static", "audio", "video"])
        nullable_fields = set(["static", "audio", "video"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
