"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ragie.types import BaseModel
from typing_extensions import TypedDict


class OnedriveDataTypedDict(TypedDict):
    drive_id: str
    folder_id: str
    folder_name: str


class OnedriveData(BaseModel):
    drive_id: str

    folder_id: str

    folder_name: str
