"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class PageBreakTypedDict(TypedDict):
    type: Literal["PageBreak"]


class PageBreak(BaseModel):
    TYPE: Annotated[
        Annotated[
            Optional[Literal["PageBreak"]], AfterValidator(validate_const("PageBreak"))
        ],
        pydantic.Field(alias="type"),
    ] = "PageBreak"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PageBreak.model_rebuild()
except NameError:
    pass
