"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .partitionlimitexceededwebhookpayload import (
    PartitionLimitExceededWebhookPayload,
    PartitionLimitExceededWebhookPayloadTypedDict,
)
import pydantic
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel
from ragie.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class PartitionLimitExceededWebhookTypedDict(TypedDict):
    nonce: str
    payload: PartitionLimitExceededWebhookPayloadTypedDict
    type: Literal["partition_limit_exceeded"]


class PartitionLimitExceededWebhook(BaseModel):
    nonce: str

    payload: PartitionLimitExceededWebhookPayload

    TYPE: Annotated[
        Annotated[
            Literal["partition_limit_exceeded"],
            AfterValidator(validate_const("partition_limit_exceeded")),
        ],
        pydantic.Field(alias="type"),
    ] = "partition_limit_exceeded"
