"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .partitionlimits import PartitionLimits, PartitionLimitsTypedDict
from datetime import datetime
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Any, Dict, List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


MetadataSchemaTypedDict = TypeAliasType(
    "MetadataSchemaTypedDict", Union[str, int, bool, List[str], Dict[str, Any]]
)


MetadataSchema = TypeAliasType(
    "MetadataSchema", Union[str, int, bool, List[str], Dict[str, Any]]
)


class PartitionTypedDict(TypedDict):
    name: str
    is_default: bool
    description: Nullable[str]
    context_aware: bool
    metadata_schema: Nullable[Dict[str, MetadataSchemaTypedDict]]
    limits: PartitionLimitsTypedDict
    limit_exceeded_at: NotRequired[Nullable[datetime]]
    r"""Timestamp when the partition exceeded its limits, if applicable."""


class Partition(BaseModel):
    name: str

    is_default: bool

    description: Nullable[str]

    context_aware: bool

    metadata_schema: Nullable[Dict[str, MetadataSchema]]

    limits: PartitionLimits

    limit_exceeded_at: OptionalNullable[datetime] = UNSET
    r"""Timestamp when the partition exceeded its limits, if applicable."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit_exceeded_at"])
        nullable_fields = set(["limit_exceeded_at", "description", "metadata_schema"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
