"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Any, Dict, List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ResponseContentTypedDict(TypedDict):
    text: str
    type: Literal["text"]
    annotations: NotRequired[List[Dict[str, Any]]]


class ResponseContent(BaseModel):
    text: str

    TYPE: Annotated[
        Annotated[Optional[Literal["text"]], AfterValidator(validate_const("text"))],
        pydantic.Field(alias="type"),
    ] = "text"

    annotations: Optional[List[Dict[str, Any]]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "annotations"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ResponseContent.model_rebuild()
except NameError:
    pass
