"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .link import Link, LinkTypedDict
from pydantic import model_serializer
from ragie.types import BaseModel, UNSET_SENTINEL
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class ScoredChunkTypedDict(TypedDict):
    text: str
    score: float
    id: str
    index: int
    document_id: str
    document_name: str
    document_metadata: Dict[str, Any]
    links: Dict[str, LinkTypedDict]
    metadata: NotRequired[Dict[str, Any]]


class ScoredChunk(BaseModel):
    text: str

    score: float

    id: str

    index: int

    document_id: str

    document_name: str

    document_metadata: Dict[str, Any]

    links: Dict[str, Link]

    metadata: Optional[Dict[str, Any]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
