"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .search import Search, SearchTypedDict
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchStepTypedDict(TypedDict):
    think: str
    current_question: str
    search: SearchTypedDict
    type: Literal["base_search"]
    errored: NotRequired[bool]


class SearchStep(BaseModel):
    think: str

    current_question: str

    search: Search

    TYPE: Annotated[
        Annotated[
            Optional[Literal["base_search"]],
            AfterValidator(validate_const("base_search")),
        ],
        pydantic.Field(alias="type"),
    ] = "base_search"

    errored: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "errored"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SearchStep.model_rebuild()
except NameError:
    pass
