"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import NotRequired, TypedDict


class Reason(str, Enum):
    CONNECTION_OVER_TOTAL_PAGE_LIMIT = "connection_over_total_page_limit"
    AUTHENTICATION_FAILED = "authentication_failed"


class SetConnectionEnabledPayloadTypedDict(TypedDict):
    enabled: bool
    reason: NotRequired[Nullable[Reason]]


class SetConnectionEnabledPayload(BaseModel):
    enabled: bool

    reason: OptionalNullable[Reason] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reason"])
        nullable_fields = set(["reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
