"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from ragie.types import BaseModel, UNSET_SENTINEL
from ragie.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StampTypedDict(TypedDict):
    type: Literal["Stamp"]
    content: NotRequired[str]
    r"""The text inside the stamp"""
    description: NotRequired[str]
    r"""A detailed description of what the visual depicts."""


class Stamp(BaseModel):
    TYPE: Annotated[
        Annotated[Optional[Literal["Stamp"]], AfterValidator(validate_const("Stamp"))],
        pydantic.Field(alias="type"),
    ] = "Stamp"

    content: Optional[str] = ""
    r"""The text inside the stamp"""

    description: Optional[str] = ""
    r"""A detailed description of what the visual depicts."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "content", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Stamp.model_rebuild()
except NameError:
    pass
