"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import List, Union
from typing_extensions import TypeAliasType


SyncFilterTypedDict = TypeAliasType("SyncFilterTypedDict", Union[str, List[str]])


SyncFilter = TypeAliasType("SyncFilter", Union[str, List[str]])
