"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updatedocumentfileparams import (
    UpdateDocumentFileParams,
    UpdateDocumentFileParamsTypedDict,
)
from ragie.types import BaseModel
from ragie.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateDocumentFileRequestTypedDict(TypedDict):
    document_id: str
    r"""The id of the document."""
    update_document_file_params: UpdateDocumentFileParamsTypedDict


class UpdateDocumentFileRequest(BaseModel):
    document_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The id of the document."""

    update_document_file_params: Annotated[
        UpdateDocumentFileParams,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]
