"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from ragie.types import BaseModel, Nullable, UNSET_SENTINEL
from typing_extensions import TypedDict


class WebhookEndpointTypedDict(TypedDict):
    id: str
    created_at: datetime
    updated_at: datetime
    name: str
    url: str
    partition_pattern: Nullable[str]
    active: bool
    secret: str


class WebhookEndpoint(BaseModel):
    id: str

    created_at: datetime

    updated_at: datetime

    name: str

    url: str

    partition_pattern: Nullable[str]

    active: bool

    secret: str

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
