"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ragie.types import BaseModel
from typing_extensions import TypedDict


class WordModalityTypedDict(TypedDict):
    word: str
    probability: float
    start: float
    end: float


class WordModality(BaseModel):
    word: str

    probability: float

    start: float

    end: float
