workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Ragie-OAS:
        inputs:
            - location: https://api.ragie.ai/openapi.json
        registry:
            location: registry.speakeasyapi.dev/ragie-ai/ragie-ai/ragie-oas
targets:
    ragie:
        target: python
        source: Ragie-OAS
        publish:
            pypi:
                token: $pypi_token
